#!/bin/bash 
###this script grant user for al privillages database if not existed
##Exit codes
##	0:	Normal termination
##	1:	Username is exited

source Database_config

function grant_user {

	USER_CHECK=$(mysql -u${DBSETTINGS["DBUSER"]} -p${DBSETTINGS["DBPASS"]} -e "SELECT EXISTS(SELECT 1 FROM mysql.user WHERE user = '${DBSETTINGS["DBUSERNAME"]}');")	
	if [[ "$DATABASE_CHECK" ]];then
		echo "this username is exited!"
		exit 1;
	else
		mysql -u${DBSETTINGS["DBUSER"]} -p${DBSETTINGS["DBPASS"]} -e "GRANT ALL PRIVILEGES ON ${DBSETTINGS["DBNAME"]}.* TO '${DBSETTINGS["DBUSERNAME"]}'@${DBSETTINGS["DBHOST"]} IDENTIFIED BY '${DBSETTINGS["USERPASS"]}';"
		echo "User has all privillages"
	fi
}

